services:
  c-dev:
    build: 
      context: ../context
      dockerfile: ../c-runtime/code-server-based/Dockerfile
    volumes:
      - c-dev-storage:/home/
    ports:
      - 8199:8080

volumes:
  c-dev-storage: