services:
  rust-dev:
    build: 
      context: ../context
      dockerfile: ../rust-runtime/code-server-based/Dockerfile
    volumes:
      - $HOME/.config:/root/.config
      - $HOME/Projects:/root/project
      # - rust-dev-storage:/home/
    ports:
      - 8202:8080
    command: --bind-addr 0.0.0.0:8080

# volumes:
#   rust-dev-storage: