services:
  tang-dev:
    build: 
      context: .
      dockerfile: code-server-based/Dockerfile
    volumes:
      - tang-dev-storage:/home/
    ports:
      - 8203:8080

volumes:
  tang-dev-storage: