services:
  python-dev:
    build: 
      context: .
      dockerfile: code-server-based/Dockerfile
    volumes:
      - python-dev-storage:/home/
    ports:
      - 8201:8080

volumes:
  python-dev-storage: