services:
  python-dev:
    build: 
      context: ../context
      dockerfile: ../python-runtime/code-server-based/Dockerfile
    volumes:
      - python-dev-storage:/home/
    ports:
      - 8204:8080

volumes:
  python-dev-storage: