services:
  android-dev:
    build: 
      context: ../context
      dockerfile: ../android-runtime/code-server-based/Dockerfile
    volumes:
      - android-dev-storage:/home/
    ports:
      - 8198:8080

volumes:
  android-dev-storage: