services:
  android-dev:
    build: 
      context: .
      dockerfile: code-server-based/Dockerfile
    volumes:
      - android-dev-storage:/home/
    ports:
      - 8198:8080

volumes:
  android-dev-storage: